- name: Import java from common role
  ansible.builtin.include_role:
    name: common
    tasks_from: java.yml

- name: install mysql
  ansible.builtin.include_role:
    name: common
    tasks_from: mysql-schema.yml