- name: Jinja templates
  hosts: localhost
  connection: local
  vars:
    x: 100
    fruits:
      - apple
      - banana
      - orange
  fruits_with_price:
    - { name: apple, price: 100 }
    - { name: banana, price: 200 }
    - { name: orange, price: 600 }
  tasks:
    - name: copy template with map
      notify: print a message
      ansible.builtin.template:
        src: sample.txt
        dest: /tmp/s3.txt
  Handlers:
    - name: print a message
      ansible.builtin.debug:
          msg: yes file has been modified