- name: Variable from inventry
  hosts: localhost
  become: yes
  connection: local
  tasks:
     - name: Install multiple packages
       dnf:
         name: "{{ item }}"
         state: present
       loop:
         - nginx
         - git
         - curl
     - name: Create multiple users
       user:
         name: "{{ item.name }}"
         uid: "{{ item.uid }}"
       loop:
         - { name: "john", uid: 2001 }
         - { name: "david", uid: 2002 }
