- name: Load pre requisites
  ansible.builtin.include_tasks: pre-reqs.yml

- name: Install GoLang & Git
  ansible.builtin.dnf:
    name:
      - golang
      - git
    state: present

- name: Compile Application Code
  ansible.builtin.shell: go mod tidy && CGO_ENABLED=0 go build -o /app/{{ component_name }} .
  args:
    chdir: /app

- name: Load pre requisites
  ansible.builtin.include_tasks: systemd.yml