- name: Install MySQL Client
  ansible.builtin.dnf:
    name: mysql8.4
    state: present

- name: Load Schema
  ansible.builtin.shell: mysql -h mysql-{{ env }}.rajukonda.online -u root -pRoboShop@1 < db/schema.sql
  args:
    chdir: /app

- name: Load App User
  ansible.builtin.shell: mysql -h mysql-{{ env }}.rajukonda.online -u root -pRoboShop@1 < db/app-user.sql
  args:
    chdir: /app