- name: Load pre requisites
  ansible.builtin.include_tasks: pre-reqs.yml

- name: Install python
  ansible.builtin.dnf:
    name:
      - python3
      - python3-pip
    state: present

- name: pip installation
  ansible.builtin.shell: pip3 install -r requirements.txt
  args:
    chdir: /app

- name: Load pre requisites
  ansible.builtin.include_tasks: systemd.yml

